### ISSUE TITLE
Multidimensional arrays are not supported ?

### ISSUE THREAD

**Issue by NeoCortexBg** [reeze/msgpack-hhvm#11]
cat ./test.php
<?php

msgpack_pack(['x' => ['y' => 1]]);

hvm -c /etc/hhvm/server.cli.ini ./test.php
[Fri Jul 15 12:55:03 2016] [hphp] [11900:7f4cd5ea32c0:0:000001] []
Warning: Not implemented source type in /tmp/test.php on line 3

Can support for multidimensional arrays be added ?

**Comment by NeoCortexBg** [comment]
Adding a case here could fix it:

https://github.com/reeze/msgpack-hhvm/blob/master/msgpack-variant.h#L139

```
case KindOfPersistentArray:
case KindOfArray: {
```

**Comment by glensc** [comment]
#12 is merged, @NeoCortexBg close this or @reeze

**Comment by reeze** [comment]
thanks for reminding.
