### ISSUE TITLE
: fatal error: hphp/runtime/base/base-includes.h: 没有那个文件或目录  #include "hphp/runtime/base/base-includes.h"

### ISSUE THREAD

**Issue by joostshao** [reeze/msgpack-hhvm#3]
: fatal error: hphp/runtime/base/base-includes.h: 没有那个文件或目录
 #include "hphp/runtime/base/base-includes.h"

**Comment by reeze** [comment]
我看了下，3.7+没有了这个文件。可以试试3.6-。新版的暂时还没有测试过。
