### ISSUE TITLE
Missing MessagePackUnpacker

### ISSUE THREAD

**Issue by rybakit** [reeze/msgpack-hhvm#7]
Please add ability to parse streams.

**Comment by reeze** [comment]
What do you mean to parse?  could you elaborate ?
https://github.com/reeze/msgpack-hhvm/blob/master/msgpack-variant.h#L32

we already have the ability to unpack a buffer.

**Comment by rybakit** [comment]
I meant unpacking a buffer. I saw the `MessagePackUnpacker` class in the tests but it's not implemented in this extension. Could you please give me an example how to unpack a buffer? Normally, with MessagePackUnpacker object I can do something like this:

``` php
$data = [
    [1, 2, 3],
    null,
    false,
];

$buffer = '';
foreach ($data as $item) {
    $buffer .= msgpack_pack($item);
}

$u = new MessagePackUnpacker();
$u->feed($buffer);

while ($u->execute()) {
    var_dump($u->data());
}
```
